# ワークフローの名前
name: Go Coverage

on:
  pull_request:
    types:
      - opened        
      - synchronize   

# ジョブ定義
jobs:
  # ジョブ名
  unit-test:
    # ジョブの実行環境の指定
    runs-on: ubuntu-latest
    # ジョブ内で実行する step を定義
    steps:
      # リポジトリからソースコードの取得
      - uses: actions/checkout@v4
      # Go の実行環境の Set up
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.20
      # テストの実行
      - name: Make Coverage
        run: make coverage
      - name: 
        uses: peter-evans/create-or-update-comment@v3
      # テストカバレッジを書き込み
      - name: Comment coverage on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: 1
          reactions: '+1'
          body-path: 'coverage.txt'
        

        

